### ISSUE TITLE
Add Dark Mode Feature

### ISSUE THREAD

**Issue by Nktech-Official** [Nktech-Official/MorseCodeTranlator#3]
add a button in Navbar to enable Dark Mode. So that players can play this game at night. Don't add skip using Black(0,0,0). Color 
Make it look like professional Dark-Mode. like Github or any other website take inspiration from where ever you want. Comment and with to assign this issue to you.

**Comment by killerkc12** [comment]
> One Issue Highlight the active page like when you open home home-tab must have a different color like Green by default when you navigate to another page That page should be highlighted see [demo](https://morse-code-translater.herokuapp.com)

I'll make it, just give me the some time

**Comment by killerkc12** [comment]
> @killerkc12 see if you can make it otherwise I will go with the aleardy linked pull request which still need some changes who ever did it first will get merged and the other will not

In just time I'll make the pr
